name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # ← yeh add karo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SECTION_NAME: waka
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: false
          STOP_AT_OTHER: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ← yeh bhi add karo